export const hubSections = [
  {
    title: "MV",
    description: "MV guides, videos, docs, examples, checklist, and FAQ.",
    path: "/v2d-resource-hub/mv",
  },
  {
    title: "EGO",
    description: "EGO guides, videos, docs, examples, checklist, and FAQ.",
    path: "/v2d-resource-hub/ego",
  },
  {
    title: "Object Scanning",
    description: "Object scanning instructions, setup guides, videos, examples, and checklist.",
    path: "/v2d-resource-hub/object-scanning",
  },
  {
    title: "Dashboard User Guide",
    description: "Guide for using the operations dashboard.",
    path: "/v2d-resource-hub/dashboard-guide",
  },
  {
    title: "Quiz",
    description: "Training quizzes for MV, EGO, and Object Scanning.",
    path: "/v2d-resource-hub/quiz",
  },
];

export const categories = [
  "Overview",
  "Videos",
  "Docs",
  "Good Examples",
  "Bad Examples",
  "Checklist",
  "FAQ",
];

export const resources = [
  // MV
  {
    id: 1,
    section: "MV",
    category: "Overview",
    title: "MV Workflow Overview",
    description: "High-level overview of the MV workflow, including calibration, setup, operator checks, recording, and quality expectations.",
    type: "doc",
    tags: ["mv", "overview", "workflow"],
    lastUpdated: "To be updated",
    url: "/docs/mv-workflow-overview.html",
  },
  {
    id: 2,
    section: "MV",
    category: "Overview",
    title: "Calibration Overview",
    description: "Overview of why calibration is used before MV data collection and how it supports camera alignment and capture quality.",
    type: "doc",
    tags: ["mv", "calibration", "overview"],
    lastUpdated: "To be updated",
    url: "/docs/mv-calibration-overview.html",
  },
  {
    id: 3,
    section: "MV",
    category: "Overview",
    title: "Data Collection Overview",
    description: "Overview of the MV data collection flow, including setup checks, operator countdown, data collector movement, bounding area rules, and quality expectations.",
    type: "doc",
    tags: ["mv", "data-collection", "overview"],
    lastUpdated: "To be updated",
    url: "/docs/mv-data-collection-overview.html",
  },


  // MV Docs
  {
    id: 54,
    section: "MV",
    category: "Docs",
    title: "MV Documentation",
    description: "Main documentation for MV calibration, data collection, operator workflow, good examples, and bad examples.",
    type: "doc",
    tags: ["mv", "documentation", "guide"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/12to7Ploqmow4y-ZhRZaIPsK8HILbiY8JTlPv6JVyziY/edit?tab=t.d866c08bjt4l",
  },
  {
    id: 4,
    section: "MV",
    category: "Docs",
    title: "MV Calibration Guide",
    description: "Instructions for camera checks, board movement, calibration rotation, stepping back, circling the area, and verifying calibration video quality.",
    type: "doc",
    tags: ["mv", "calibration", "guide"],
    lastUpdated: "To be updated",
    url: "/docs/mv-calibration-guide.html",
  },
  {
    id: 5,
    section: "MV",
    category: "Docs",
    title: "MV Data Collector Guidelines",
    description: "Guidelines for object requirements, clothing, hair, bounding area rules, object visibility, timing, and movement quality.",
    type: "doc",
    tags: ["mv", "data-collector", "guidelines"],
    lastUpdated: "To be updated",
    url: "/docs/mv-data-collector-guidelines.html",
  },
  {
    id: 6,
    section: "MV",
    category: "Docs",
    title: "MV Operator Guide",
    description: "Operator instructions for connecting to Nova Orin, launching the recorder, opening the monitoring UI, starting recordings, giving countdowns, ending sessions, and communicating with the data collector.",
    type: "doc",
    tags: ["mv", "operator", "guide"],
    lastUpdated: "To be updated",
    url: "/docs/mv-operator-guide.html",
  },

  // MV Good Examples
  {
    id: 7,
    section: "MV",
    category: "Good Examples",
    title: "Stays Inside the Bounding Area",
    description: "The data collector remains inside the designated circle inside the tape from the start to the end of the sequence.",
    type: "example",
    tags: ["mv", "good-example", "bounds"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 8,
    section: "MV",
    category: "Good Examples",
    title: "Target Object Stays Visible",
    description: "At the start of each sequence, the target object is not blocked from any camera view and remains visible during the task.",
    type: "example",
    tags: ["mv", "good-example", "visibility"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 9,
    section: "MV",
    category: "Good Examples",
    title: "Slow and Natural Movements",
    description: "The data collector uses slow, natural, consistent movements without sudden stops, jerky motion, or abrupt speed changes.",
    type: "example",
    tags: ["mv", "good-example", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // MV Bad Examples
  {
    id: 11,
    section: "MV",
    category: "Bad Examples",
    title: "Going Out of Bounds",
    description: "Bad data collection occurs when the data collector steps outside the allowed marked bounding area during the sequence.",
    type: "example",
    tags: ["mv", "bad-example", "bounds"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 12,
    section: "MV",
    category: "Bad Examples",
    title: "Improper Attire",
    description: "Avoid baggy clothing, loose tops, shorts, skirts, dresses, high heels, chunky footwear, badges, accessories, or hair/clothing that blocks the interaction.",
    type: "example",
    tags: ["mv", "bad-example", "attire"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 13,
    section: "MV",
    category: "Bad Examples",
    title: "Unnatural Motions",
    description: "Sudden stops, jerky movement, abrupt direction changes, and inconsistent speed can create unnatural trajectories.",
    type: "example",
    tags: ["mv", "bad-example", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // MV Checklist
  {
    id: 17,
    section: "MV",
    category: "Checklist",
    title: "Calibration Checklist",
    description: "Stand in the center, secure all cameras, remove other chessboard patterns, move the board slowly, complete rotation and circling movement, then close the process.",
    type: "checklist",
    tags: ["mv", "checklist", "calibration"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 18,
    section: "MV",
    category: "Checklist",
    title: "Before Data Collection Checklist",
    description: "Verify calibration video quality, confirm the object is pre-scanned, ensure the object is not duplicated, and prepare the bounding area.",
    type: "checklist",
    tags: ["mv", "checklist", "before-collection"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 19,
    section: "MV",
    category: "Checklist",
    title: "Data Collector Checklist",
    description: "Stand inside the marked bounding area, wear fitted clothing, remove badge, avoid baggy clothes/shorts/skirts/dresses/loose tops/high heels/chunky footwear, and move slowly/naturally.",
    type: "checklist",
    tags: ["mv", "checklist", "data-collector"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 20,
    section: "MV",
    category: "Checklist",
    title: "Operator Checklist",
    description: "Start recording first, give a 3 second countdown, confirm the object is not blocked, listen for stop signal, end recording, and shut down equipment at end of day.",
    type: "checklist",
    tags: ["mv", "checklist", "operator"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // MV FAQ
  {
    id: 21,
    section: "MV",
    category: "FAQ",
    title: "How long should each sequence be?",
    description: "Each sequence is expected to be about 30 seconds. Some variation is acceptable, but following the action description takes priority.",
    type: "faq",
    tags: ["mv", "faq", "sequence-length"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 22,
    section: "MV",
    category: "FAQ",
    title: "When should the data collector start moving?",
    description: "The operator should start recording first, then give a 3 second countdown before signaling the data collector to start moving.",
    type: "faq",
    tags: ["mv", "faq", "countdown"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 23,
    section: "MV",
    category: "FAQ",
    title: "What should be checked before collecting data?",
    description: "Verify the calibration video is good quality before starting data collection.",
    type: "faq",
    tags: ["mv", "faq", "calibration"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // EGO
  {
    id: 8,
    section: "EGO",
    category: "Overview",
    title: "EGO Workflow Overview",
    description: "High-level overview of the EGO workflow, including setup, operator checks, data collector movement, gesture timing, and recording quality.",
    type: "doc",
    tags: ["ego", "overview", "workflow"],
    lastUpdated: "To be updated",
    url: "/docs/ego-workflow-overview.html",
  },
  {
    id: 9,
    section: "EGO",
    category: "Overview",
    title: "EGO Data Collection Overview",
    description: "Overview of operator and data collector responsibilities before, during, and after EGO recording.",
    type: "doc",
    tags: ["ego", "data-collection", "overview"],
    lastUpdated: "To be updated",
    url: "/docs/ego-data-collection-overview.html",
  },

  // EGO Docs
  {
    id: 10,
    section: "EGO",
    category: "Docs",
    title: "EGO Documentation",
    description: "Main EGO documentation covering recording workflow, gesture timing, camera visibility, movement principles, speed guidance, and quality rules.",
    type: "doc",
    tags: ["ego", "documentation", "guide"],
    lastUpdated: "To be updated",
    url: "/docs/ego-documentation.html",
  },
  {
    id: 11,
    section: "EGO",
    category: "Docs",
    title: "EGO Data Collector Guide",
    description: "Guide for data collector responsibilities, start/end pose, visibility requirements, movement principles, speed guidance, and episode duration.",
    type: "doc",
    tags: ["ego", "data-collector", "guide"],
    lastUpdated: "To be updated",
    url: "/docs/ego-data-collector-guide.html",
  },
  {
    id: 12,
    section: "EGO",
    category: "Docs",
    title: "EGO Operator Guide",
    description: "Guide for operator checks, frame visibility, recording quality, and redo rules.",
    type: "doc",
    tags: ["ego", "operator", "guide"],
    lastUpdated: "To be updated",
    url: "/docs/ego-operator-guide.html",
  },

  // EGO Good Examples
  {
    id: 14,
    section: "EGO",
    category: "Good Examples",
    title: "Correct Start Pose and Return Pose",
    description: "At the start of each session, hold palms facing each other with fingers bent for 3 seconds. At the end, return to the same pose.",
    type: "example",
    tags: ["ego", "good-example", "gesture"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 15,
    section: "EGO",
    category: "Good Examples",
    title: "Smooth and Natural Grasp",
    description: "Use smooth, consistent, natural, and deliberate grasp techniques so the action is easy to understand.",
    type: "example",
    tags: ["ego", "good-example", "grasp"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 16,
    section: "EGO",
    category: "Good Examples",
    title: "Consistent Controlled Movement",
    description: "Move at a consistent speed throughout the recording. Movements should be fluid, continuous, and related to the task.",
    type: "example",
    tags: ["ego", "good-example", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // EGO Bad Examples
  {
    id: 44,
    section: "EGO",
    category: "Bad Examples",
    title: "Jerky or Fast Movements",
    description: "Avoid quick, jerky, or unexpected movements. These can lead to errors, auto-deletions, and lower-quality data.",
    type: "example",
    tags: ["ego", "bad-example", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 45,
    section: "EGO",
    category: "Bad Examples",
    title: "Hands or Wrists Not Visible",
    description: "Avoid covering fingers or wrists with clothing. Hands and wrists should stay fully visible inside the head-mounted camera view.",
    type: "example",
    tags: ["ego", "bad-example", "visibility"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 46,
    section: "EGO",
    category: "Bad Examples",
    title: "Extra Hands or People in View",
    description: "No other person or extra hand should be visible inside the head-mounted camera view during the recording.",
    type: "example",
    tags: ["ego", "bad-example", "camera-view"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 47,
    section: "EGO",
    category: "Bad Examples",
    title: "Unnecessary Waist Rotation",
    description: "Avoid unnecessary waist rotation. The video should remain steady and not become unstable because of body movement.",
    type: "example",
    tags: ["ego", "bad-example", "waist-rotation"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 48,
    section: "EGO",
    category: "Bad Examples",
    title: "Making a Fist",
    description: "When not interacting with objects, avoid clenching the hand into a fist. Keep fingers relaxed and visible.",
    type: "example",
    tags: ["ego", "bad-example", "fist"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // EGO Checklist
  {
    id: 49,
    section: "EGO",
    category: "Checklist",
    title: "Before Recording Checklist",
    description: "Check that the head-mounted camera is ready, wrists are visible, fingers are not covered, and no extra hands or people are in view.",
    type: "checklist",
    tags: ["ego", "checklist", "before-recording"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 50,
    section: "EGO",
    category: "Checklist",
    title: "Start and End Gesture Checklist",
    description: "Hold palms facing each other with fingers bent at the start for 3 seconds. At the end, return to the same pose.",
    type: "checklist",
    tags: ["ego", "checklist", "gesture"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 51,
    section: "EGO",
    category: "Checklist",
    title: "Movement Quality Checklist",
    description: "Use deliberate, smooth, and consistent movement. Default to teaching speed, avoid stop-start motion, and target 10–40 seconds per episode unless stated otherwise.",
    type: "checklist",
    tags: ["ego", "checklist", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // EGO FAQ
  {
    id: 52,
    section: "EGO",
    category: "FAQ",
    title: "How long should the start pose be held?",
    description: "Hold the start pose steadily for 3 seconds. At the end, return to the same pose, but no 3 second hold is required.",
    type: "faq",
    tags: ["ego", "faq", "gesture"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 53,
    section: "EGO",
    category: "FAQ",
    title: "What should always stay visible?",
    description: "Fingers and wrists should stay fully visible and not be covered by clothing. The task should remain within the head-mounted camera view.",
    type: "faq",
    tags: ["ego", "faq", "visibility"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 54,
    section: "EGO",
    category: "FAQ",
    title: "What should happen if hands or objects go out of frame?",
    description: "The sequence should be deleted and redone if hands, wrists, objects, or important task interaction leave the frame.",
    type: "faq",
    tags: ["ego", "faq", "frame"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // Object Scanning
  {
    id: 15,
    section: "Object Scanning",
    category: "Overview",
    title: "Object Scanning Overview",
    description: "Overview of the EINSTAR scanning workflow, Blender conversion steps, and BundleSDF setup.",
    type: "doc",
    tags: ["object-scanning", "overview", "einstar", "blender"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 16,
    section: "Object Scanning",
    category: "Overview",
    title: "EINSTAR Scanning Guidelines",
    description: "Guidelines for preparing the environment, scanning slowly, keeping the object visible, and capturing multiple views.",
    type: "doc",
    tags: ["object-scanning", "guidelines", "einstar"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 17,
    section: "Object Scanning",
    category: "Overview",
    title: "BundleSDF Setup Overview",
    description: "Setup notes for backpack straps, power banks, phone connection, browser UI, test recording, and upload flow.",
    type: "doc",
    tags: ["object-scanning", "bundlesdf", "setup"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },

  // Object Scanning Videos
  {
    id: 18,
    section: "Object Scanning",
    category: "Videos",
    title: "Scanning Example Video",
    description: "Reference video showing an example object scanning workflow.",
    type: "video",
    tags: ["object-scanning", "scanning-example"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/scanning-example.mp4",
  },
  {
    id: 19,
    section: "Object Scanning",
    category: "Videos",
    title: "Project Alignment Video",
    description: "Video tutorial for aligning different scan projects/views.",
    type: "video",
    tags: ["object-scanning", "alignment"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/project-alignment.mp4",
  },
  {
    id: 20,
    section: "Object Scanning",
    category: "Videos",
    title: "Mesh Settings Video",
    description: "Video tutorial for mesh settings and generating the final mesh.",
    type: "video",
    tags: ["object-scanning", "mesh"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/mesh-settings.mp4",
  },
  {
    id: 21,
    section: "Object Scanning",
    category: "Videos",
    title: "Post-Processing Video",
    description: "Video tutorial for post-processing, hole filling, and reviewing the final mesh.",
    type: "video",
    tags: ["object-scanning", "post-processing"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/post-processing.mp4",
  },
  {
    id: 22,
    section: "Object Scanning",
    category: "Videos",
    title: "Exporting the Scan Video",
    description: "Video tutorial for exporting the completed scan file.",
    type: "video",
    tags: ["object-scanning", "export"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/export.mp4",
  },
  {
    id: 23,
    section: "Object Scanning",
    category: "Videos",
    title: "Using Blender Video",
    description: "Video tutorial for using Blender to convert object scan files.",
    type: "video",
    tags: ["object-scanning", "blender"],
    lastUpdated: "To be updated",
    url: "/videos/object-scanning/blender.mp4",
  },

  // Object Scanning Docs
  {
    id: 24,
    section: "Object Scanning",
    category: "Docs",
    title: "EINSTAR and BLENDER Documentation",
    description: "Full documentation for EINSTAR scanning, Blender conversion, calibration, and BundleSDF setup.",
    type: "doc",
    tags: ["object-scanning", "einstar", "blender", "documentation"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 25,
    section: "Object Scanning",
    category: "Docs",
    title: "Download EXStar Hub",
    description: "Download the EXStar Hub desktop software needed to connect and use the EINSTAR scanner.",
    type: "link",
    tags: ["object-scanning", "exstar", "software", "download"],
    lastUpdated: "To be updated",
    url: "https://support.einstar.com/support/solutions/articles/60001635292-download-exstar-hub-desktop-software-for-einstar-rockit-einstar-2-",
  },
  {
    id: 26,
    section: "Object Scanning",
    category: "Docs",
    title: "Download Blender",
    description: "Download Blender, used to convert exported .OBJ scan files into .GLB files.",
    type: "link",
    tags: ["object-scanning", "blender", "software", "download"],
    lastUpdated: "To be updated",
    url: "https://www.blender.org/download/",
  },
  {
    id: 27,
    section: "Object Scanning",
    category: "Docs",
    title: "EINSTAR Calibration Steps",
    description: "Calibration workflow for the EINSTAR scanner. Calibration should be done weekly or when unsure.",
    type: "doc",
    tags: ["object-scanning", "einstar", "calibration"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 28,
    section: "Object Scanning",
    category: "Docs",
    title: "Blender OBJ to GLB Steps",
    description: "Steps for importing .OBJ files, setting origin, scaling, reducing vertices, and exporting .GLB files.",
    type: "doc",
    tags: ["object-scanning", "blender", "glb", "obj"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },

  // Object Scanning Good Examples
  {
    id: 29,
    section: "Object Scanning",
    category: "Good Examples",
    title: "Objects That Scan Well",
    description: "Good scanning objects are non-reflective, lighter in color, feature-rich, non-symmetrical, opaque, and small to medium sized.",
    type: "example",
    tags: ["object-scanning", "good-example", "objects"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 30,
    section: "Object Scanning",
    category: "Good Examples",
    title: "Good Scanning Environment",
    description: "Use uniform diffuse lighting, place the object on a flat surface, leave room to move around, and keep feature-rich objects nearby.",
    type: "example",
    tags: ["object-scanning", "good-example", "environment"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 31,
    section: "Object Scanning",
    category: "Good Examples",
    title: "Good Scanning Behavior",
    description: "Move slowly, watch the display, keep the green overlay visible, pause when needed, and capture the object from multiple angles.",
    type: "example",
    tags: ["object-scanning", "good-example", "workflow"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // Object Scanning Bad Examples
  {
    id: 32,
    section: "Object Scanning",
    category: "Bad Examples",
    title: "Objects That Do Not Scan Well",
    description: "Avoid black, reflective, transparent, featureless, completely symmetrical, very large, or very small objects when possible.",
    type: "example",
    tags: ["object-scanning", "bad-example", "objects"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 33,
    section: "Object Scanning",
    category: "Bad Examples",
    title: "Moving Too Fast",
    description: "Moving too fast can cause tracking issues or a purple overlay because the scanner cannot find enough features to align.",
    type: "example",
    tags: ["object-scanning", "bad-example", "movement"],
    lastUpdated: "To be updated",
    url: "#",
  },
  {
    id: 34,
    section: "Object Scanning",
    category: "Bad Examples",
    title: "Losing Object Tracking",
    description: "If the scanner loses positioning, duplicate geometry can appear. You may need to crop it out or restart the scan.",
    type: "example",
    tags: ["object-scanning", "bad-example", "tracking"],
    lastUpdated: "To be updated",
    url: "#",
  },

  // Object Scanning Checklist
  {
    id: 35,
    section: "Object Scanning",
    category: "Checklist",
    title: "Before Scanning Checklist",
    description: "Check lighting, object placement, flat surface, surrounding feature-rich items, scanner battery, and gloves.",
    type: "checklist",
    tags: ["object-scanning", "checklist", "before-scanning"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 36,
    section: "Object Scanning",
    category: "Checklist",
    title: "EINSTAR Setup Checklist",
    description: "Install EXStar Hub, power on scanner, connect to Wi-Fi, confirm green connection, create project, and choose scan settings.",
    type: "checklist",
    tags: ["object-scanning", "checklist", "einstar"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 37,
    section: "Object Scanning",
    category: "Checklist",
    title: "Scanning Workflow Checklist",
    description: "Preview green overlay, start scan, move slowly, pause when needed, crop environment, capture multiple views, align, mesh, and export.",
    type: "checklist",
    tags: ["object-scanning", "checklist", "workflow"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 38,
    section: "Object Scanning",
    category: "Checklist",
    title: "Blender Export Checklist",
    description: "Import .OBJ, set origin, scale object, reduce vertices if needed, apply transforms, remove extra objects, and export .GLB.",
    type: "checklist",
    tags: ["object-scanning", "checklist", "blender"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 39,
    section: "Object Scanning",
    category: "Checklist",
    title: "BundleSDF Setup Checklist",
    description: "Connect backpack straps, power banks, phone Wi-Fi, browser UI, set time, test recording, upload valid files, and power off.",
    type: "checklist",
    tags: ["object-scanning", "checklist", "bundlesdf"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },

  // Object Scanning FAQ
  {
    id: 40,
    section: "Object Scanning",
    category: "FAQ",
    title: "How often should the EINSTAR scanner be calibrated?",
    description: "The scanner should be calibrated every week or whenever you are unsure of the last calibration date.",
    type: "faq",
    tags: ["object-scanning", "faq", "calibration"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 41,
    section: "Object Scanning",
    category: "FAQ",
    title: "What should I do if the green overlay is not visible?",
    description: "Return to the home screen, power off the scanner, and repeat the setup steps before scanning.",
    type: "faq",
    tags: ["object-scanning", "faq", "overlay"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 42,
    section: "Object Scanning",
    category: "FAQ",
    title: "What should I do if the scanner loses tracking?",
    description: "Try returning to a position already scanned. If duplicates appear, crop them out or restart the scan if needed.",
    type: "faq",
    tags: ["object-scanning", "faq", "tracking"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
  {
    id: 43,
    section: "Object Scanning",
    category: "FAQ",
    title: "What file format should be exported from EINSTAR?",
    description: "Export the scan as an .OBJ file, then use Blender to convert it into a .GLB file.",
    type: "faq",
    tags: ["object-scanning", "faq", "export"],
    lastUpdated: "To be updated",
    url: "https://docs.google.com/document/d/1U-L8FbZR5IRTluqlZW0cK8yenZoaLWWz2QZ6wbmMovw/edit?tab=t.0#heading=h.urz7lcyc2tri",
  },
];


// Additional example media slots
resources.push(
  {
    id: 1001,
    section: "MV",
    category: "Good Examples",
    title: "MV Good Example Video 1",
    description: "Video example showing correct MV data collection behavior.",
    type: "video",
    tags: ["mv", "good-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-good-example-1.mp4",
  },
  {
    id: 1002,
    section: "MV",
    category: "Good Examples",
    title: "MV Good Example Video 2",
    description: "Second video example showing correct MV data collection behavior.",
    type: "video",
    tags: ["mv", "good-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-good-example-2.mp4",
  },
  {
    id: 1003,
    section: "MV",
    category: "Bad Examples",
    title: "MV Bad Example Video 1",
    description: "Video example showing MV collection mistakes to avoid.",
    type: "video",
    tags: ["mv", "bad-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-bad-example-1.mp4",
  },
  {
    id: 1004,
    section: "MV",
    category: "Bad Examples",
    title: "MV Bad Example Video 2",
    description: "Second video example showing MV collection mistakes to avoid.",
    type: "video",
    tags: ["mv", "bad-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-bad-example-2.mp4",
  },

  {
    id: 1005,
    section: "EGO",
    category: "Good Examples",
    title: "EGO Good Example Video 1",
    description: "Video example showing correct EGO recording behavior.",
    type: "video",
    tags: ["ego", "good-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-good-example-1.mp4",
  },
  {
    id: 1006,
    section: "EGO",
    category: "Good Examples",
    title: "EGO Good Example Video 2",
    description: "Second video example showing correct EGO recording behavior.",
    type: "video",
    tags: ["ego", "good-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-good-example-2.mp4",
  },
  {
    id: 1007,
    section: "EGO",
    category: "Bad Examples",
    title: "EGO Bad Example Video 1",
    description: "Video example showing EGO recording mistakes to avoid.",
    type: "video",
    tags: ["ego", "bad-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-bad-example-1.mp4",
  },
  {
    id: 1008,
    section: "EGO",
    category: "Bad Examples",
    title: "EGO Bad Example Video 2",
    description: "Second video example showing EGO recording mistakes to avoid.",
    type: "video",
    tags: ["ego", "bad-example", "video"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-bad-example-2.mp4",
  },

  {
    id: 1009,
    section: "Object Scanning",
    category: "Good Examples",
    title: "Object Scanning Good Example 3D Model 1",
    description: "3D model example showing a good object scanning result.",
    type: "model",
    tags: ["object-scanning", "good-example", "photo"],
    lastUpdated: "To be updated",
    url: "/models/object-scanning/object-good-example-1.glb",
  },
  {
    id: 1010,
    section: "Object Scanning",
    category: "Good Examples",
    title: "Object Scanning Good Example 3D Model 2",
    description: "Second 3D model example showing a good object scanning result.",
    type: "model",
    tags: ["object-scanning", "good-example", "photo"],
    lastUpdated: "To be updated",
    url: "/models/object-scanning/object-good-example-2.glb",
  },
  {
    id: 1011,
    section: "Object Scanning",
    category: "Bad Examples",
    title: "Object Scanning Bad Example 3D Model 1",
    description: "3D model example showing an object scanning result issue to avoid.",
    type: "model",
    tags: ["object-scanning", "bad-example", "photo"],
    lastUpdated: "To be updated",
    url: "/models/object-scanning/object-bad-example-1.glb",
  },
  {
    id: 1012,
    section: "Object Scanning",
    category: "Bad Examples",
    title: "Object Scanning Bad Example 3D Model 2",
    description: "Second 3D model example showing an object scanning result issue to avoid.",
    type: "model",
    tags: ["object-scanning", "bad-example", "photo"],
    lastUpdated: "To be updated",
    url: "/models/object-scanning/object-bad-example-2.glb",
  }
);



// MV example videos also shown under Videos
resources.push(
  {
    id: 1101,
    section: "MV",
    category: "Videos",
    title: "Good Example: MV Data Collection",
    description: "Video showing a good MV data collection example with correct movement and visibility.",
    type: "video",
    tags: ["mv", "video", "good-example"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-good-example-1.mp4",
  },
  {
    id: 1102,
    section: "MV",
    category: "Videos",
    title: "Bad Example 1: MV Data Collection",
    description: "Video showing an MV data collection issue to avoid.",
    type: "video",
    tags: ["mv", "video", "bad-example"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-bad-example-1.mp4",
  },
  {
    id: 1103,
    section: "MV",
    category: "Videos",
    title: "Bad Example 2: MV Data Collection",
    description: "Second video showing an MV data collection issue to avoid.",
    type: "video",
    tags: ["mv", "video", "bad-example"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-bad-example-2.mp4",
  }
);



// MV calibration and output videos
resources.push(
  {
    id: 1110,
    section: "MV",
    category: "Videos",
    title: "MV Calibration Video",
    description: "Video showing the MV calibration process and expected calibration movement.",
    type: "video",
    tags: ["mv", "video", "calibration"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-calibration.mp4",
  },
  {
    id: 1111,
    section: "MV",
    category: "Videos",
    title: "Sample Output Visualization",
    description: "Video showing a sample output visualization for MV data review.",
    type: "video",
    tags: ["mv", "video", "sample-output", "visualization"],
    lastUpdated: "To be updated",
    url: "/videos/mv/sample-output-visualization.mp4",
  }
);



resources.push(
  {
    id: 1112,
    section: "MV",
    category: "Videos",
    title: "Good Example 2: MV Data Collection",
    description: "Second video showing a good MV data collection example.",
    type: "video",
    tags: ["mv", "video", "good-example"],
    lastUpdated: "To be updated",
    url: "/videos/mv/mv-good-example-2.mp4",
  }
);



resources.push(
  {
    id: 1121,
    section: "EGO",
    category: "Videos",
    title: "Bad Example 1: EGO Recording",
    description: "Video showing an EGO recording issue to avoid.",
    type: "video",
    tags: ["ego", "video", "bad-example"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-bad-example-1.mp4",
  },
  {
    id: 1122,
    section: "EGO",
    category: "Videos",
    title: "Bad Example 2: EGO Recording",
    description: "Second video showing an EGO recording issue to avoid.",
    type: "video",
    tags: ["ego", "video", "bad-example"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-bad-example-2.mp4",
  }
);



resources.push(
  {
    id: 1123,
    section: "EGO",
    category: "Videos",
    title: "Good Example 1: EGO Recording",
    description: "Video showing a good EGO recording example.",
    type: "video",
    tags: ["ego", "video", "good-example"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-good-example-1.mp4",
  },
  {
    id: 1124,
    section: "EGO",
    category: "Videos",
    title: "Good Example 2: EGO Recording",
    description: "Second video showing a good EGO recording example.",
    type: "video",
    tags: ["ego", "video", "good-example"],
    lastUpdated: "To be updated",
    url: "/videos/ego/ego-good-example-2.mp4",
  }
);




export const dashboardGuideItems = [];

export const quizzes = [
  {
    id: 1,
    title: "MV Quiz",
    description: "Validate understanding of MV workflow requirements.",
    questionsCount: 13,
  },
  {
    id: 2,
    title: "EGO Quiz",
    description: "Validate understanding of EGO workflow requirements.",
    questionsCount: 10,
  },
  {
    id: 3,
    title: "Object Scanning Quiz",
    description: "Validate understanding of object scanning workflow requirements.",
    questionsCount: 10,
  },
];
